### ISSUE TITLE
アーティスト詳細情報

### ISSUE THREAD

**Issue by HaruNakano** [shirayamamusicvillage/shirayamamusicvillage.github.io#10]

**Comment by HaruNakano** [comment]
https://docs.google.com/spreadsheets/d/1gnahI5FsBGX-_iMCjOg5N0fQMMI-jL4dTQ_vM_XgvVQ/edit?usp=sharing

**Comment by taisukef** [comment]
参考
https://yatsusugi.sub.jp/

**Comment by taisukef** [comment]
詳細画面、作成しました
画像や情報はこちらを編集すると反映されます

https://github.com/shirayamamusicvillage/shirayamamusicvillage.github.io/blob/main/csv/artists.csv
