### ISSUE TITLE
OGP画像中の日程が延期後のものになっていない

### ISSUE THREAD

**Issue by yudai-nkt** [shirayamamusicvillage/shirayamamusicvillage.github.io#13]
タイトル通りですが，[OGP画像](https://github.com/shirayamamusicvillage/shirayamamusicvillage.github.io/blob/fa86185c425d2e0ba0658fb6b42115f72f476f70/img/smv-ogp.png)が8/28, 29開催のままなことに気付いたのでご報告です．

**Comment by taisukef** [comment]
ファイル名を変えた新しいOGP画像を作って、index.html内のファイル名を変更し、デバッグツールで再読み込みすることで修正可能です

**Comment by taisukef** [comment]
https://github.com/shirayamamusicvillage/shirayamamusicvillage.github.io/commit/8778a69b68877f3a781a9ea79ba8173dde08e295
更新完了です
